---
- name: install app
  hosts: ansible_host
  gather_facts: no
  become: true
  tasks:
  - name: Install a list of packages
    yum:
      name: httpd
      state: present
  - name: start httpd
    service:
      name: httpd
      state: started
